### ISSUE TITLE
Error on create profile

### ISSUE THREAD

**Issue by codingjeremy** [android/enterprise-samples#15]
<a href="https://github.com/jaelsonapolinario"><img src="https://avatars2.githubusercontent.com/u/6399078?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jaelsonapolinario](https://github.com/jaelsonapolinario)**
_Tuesday May 31, 2016 at 19:28 GMT_
_Originally opened as https://github.com/googlesamples/android-AppRestrictionEnforcer/issues/2_

----

05-31 16:18:37.959 4397-4540/com.example.android.apprestrictionenforcer D/OpenGLRenderer: endAllStagingAnimators on 0xb7808448 (RippleDrawable) with handle 0xb7806b40
05-31 16:19:27.108 5980-5980/com.example.android.apprestrictionenforcer E/InstantRun: Failed to create directory /data/data/com.example.android.apprestrictionenforcer/files/instant-run/dex
05-31 16:19:27.129 5980-5980/com.example.android.apprestrictionenforcer A/InstantRun: Couldn't create dex code folder
05-31 16:19:27.149 5980-5980/com.example.android.apprestrictionenforcer D/AndroidRuntime: Shutting down VM

```
                                                                                      --------- beginning of crash
```

05-31 16:19:27.151 5980-5980/com.example.android.apprestrictionenforcer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                          Process: com.example.android.apprestrictionenforcer, PID: 5980
                                                                                          java.lang.RuntimeException: Unable to instantiate receiver com.example.android.apprestrictionenforcer.EnforcerDeviceAdminReceiver: java.lang.ClassNotFoundException: Didn't find class "com.example.android.apprestrictionenforcer.EnforcerDeviceAdminReceiver" on path: DexPathList[[zip file "/data/app/com.example.android.apprestrictionenforcer-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                                              at android.app.ActivityThread.handleReceiver(ActivityThread.java:2620)
                                                                                              at android.app.ActivityThread.access$1700(ActivityThread.java:155)
                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.android.apprestrictionenforcer.EnforcerDeviceAdminReceiver" on path: DexPathList[[zip file "/data/app/com.example.android.apprestrictionenforcer-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                              at android.app.ActivityThread.handleReceiver(ActivityThread.java:2615)
                                                                                              at android.app.ActivityThread.access$1700(ActivityThread.java:155) 
                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394) 
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                              at android.os.Looper.loop(Looper.java:135) 
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
                                                                                            Suppressed: java.lang.ClassNotFoundException: com.example.android.apprestrictionenforcer.EnforcerDeviceAdminReceiver
                                                                                              at java.lang.Class.classForName(Native Method)
                                                                                              at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                              at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                                    ... 11 more
                                                                                           Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by codingjeremy** [comment]
<a href="https://github.com/ndubbaka"><img src="https://avatars1.githubusercontent.com/u/545961?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ndubbaka](https://github.com/ndubbaka)**
_Tuesday Feb 14, 2017 at 21:22 GMT_

----

I have the same issue here
```
02-14 16:21:04.323 6810-6810/com.example.android.apprestrictionenforcer E/InstantRun: Failed to create directory /data/data/com.example.android.apprestrictionenforcer/files/instant-run/dex
02-14 16:21:04.324 6810-6810/com.example.android.apprestrictionenforcer A/InstantRun: Couldn't create dex code folder
02-14 16:21:04.329 6810-6810/com.example.android.apprestrictionenforcer W/InstantRun: No instant run dex files added to classpath
02-14 16:21:04.348 6810-6810/com.example.android.apprestrictionenforcer E/InstantRun: IO Error creating local socket at com.example.android.apprestrictionenforcer
                                                                                      java.io.IOException: Address already in use
                                                                                          at android.net.LocalSocketImpl.bindLocal(Native Method)
                                                                                          at android.net.LocalSocketImpl.bind(LocalSocketImpl.java:309)
                                                                                          at android.net.LocalServerSocket.<init>(LocalServerSocket.java:48)
                                                                                          at com.android.tools.fd.runtime.Server.<init>(Server.java:94)
                                                                                          at com.android.tools.fd.runtime.Server.create(Server.java:88)
                                                                                          at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:359)
                                                                                          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4593)
                                                                                          at android.app.ActivityThread.access$1600(ActivityThread.java:154)
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
02-14 16:21:04.350 6810-6810/com.example.android.apprestrictionenforcer D/AndroidRuntime: Shutting down VM
02-14 16:21:04.357 6810-6810/com.example.android.apprestrictionenforcer E/AndroidRuntime: FATAL EXCEPTION: main
```

**Comment by codingjeremy** [comment]
<a href="https://github.com/ndubbaka"><img src="https://avatars1.githubusercontent.com/u/545961?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ndubbaka](https://github.com/ndubbaka)**
_Tuesday Feb 14, 2017 at 21:29 GMT_

----

Downgrading gradle to 2.0.0 worked for me
http://stackoverflow.com/questions/37059611/gradle-plugin-2-1-0-app-crashes-on-launch
